# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 01:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommenderfile',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 4, 26, 1, 52, 9, 881985, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
