# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 20:58
from __future__ import unicode_literals

import accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_attribute_1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='attribute_1',
        ),
        migrations.AddField(
            model_name='user',
            name='collaborative',
            field=accounts.models.IntegerRangeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='language',
            field=accounts.models.IntegerRangeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='outdoor',
            field=accounts.models.IntegerRangeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='strength',
            field=accounts.models.IntegerRangeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='transportation',
            field=accounts.models.IntegerRangeField(blank=True, null=True),
        ),
    ]
