# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 21:05
from __future__ import unicode_literals

from django.db import migrations, models
import tasks.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('attribute_1', tasks.models.IntegerRangeField(blank=True, null=True)),
                ('attribute_2', tasks.models.IntegerRangeField(blank=True, null=True)),
                ('attribute_3', tasks.models.IntegerRangeField(blank=True, null=True)),
                ('attribute_4', tasks.models.IntegerRangeField(blank=True, null=True)),
                ('attribute_5', tasks.models.IntegerRangeField(blank=True, null=True)),
                ('attribute_6', tasks.models.IntegerRangeField(blank=True, null=True)),
                ('attribute_7', tasks.models.IntegerRangeField(blank=True, null=True)),
                ('attribute_8', tasks.models.IntegerRangeField(blank=True, null=True)),
                ('attribute_9', tasks.models.IntegerRangeField(blank=True, null=True)),
                ('attribute_10', tasks.models.IntegerRangeField(blank=True, null=True)),
            ],
        ),
    ]
