# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 05:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_task_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='attribute_1',
            new_name='collaborative',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='attribute_10',
            new_name='language',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='attribute_2',
            new_name='outdoor',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='attribute_3',
            new_name='strength',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='attribute_4',
            new_name='transportation',
        ),
        migrations.RemoveField(
            model_name='task',
            name='attribute_5',
        ),
        migrations.RemoveField(
            model_name='task',
            name='attribute_6',
        ),
        migrations.RemoveField(
            model_name='task',
            name='attribute_7',
        ),
        migrations.RemoveField(
            model_name='task',
            name='attribute_8',
        ),
        migrations.RemoveField(
            model_name='task',
            name='attribute_9',
        ),
    ]
